### ISSUE TITLE
Add testing framework for MIMIC-IV ETL

### ISSUE THREAD

**Issue by tompollard** [Medical-Event-Data-Standard/meds_etl#1]
We could consider adding tests for these ETLs, e.g. the MIMIC-IV ETL should be reproducible using the open MIMIC-IV demo at: https://doi.org/10.13026/dp1f-ex47. 

If this sounds like a good idea, we could either (1) include a copy of the data in this repo (2) make the tests dependent on an externally hosted version of the data. 

My preference is 2 I think, just to help keep this repo clean.  

The MIMIC-IV demo doesn't appear to be on BigQuery at the moment, but we can arrange this. We could then set up GitHub actions to run the tests against BigQuery.

**Comment by EthanSteinberg** [comment]
Yep, this is a really good idea! 

We can use the MIMIC demo for MIMIC and a synthetic OMOP dataset for OMOP. I already have a synthetic OMOP on hand from https://github.com/som-shahlab/femr/tree/main/tutorials/input/omop which will probably be sufficient for that.

**Comment by EthanSteinberg** [comment]
https://github.com/Medical-Event-Data-Standard/meds_etl/actions seems to now be working!

**Comment by tompollard** [comment]
Perfect, thanks Ethan! I'll have a go at adding a couple of MIMIC tests later today.
