### ISSUE TITLE
ValueError: The provided OMOP dataset is missing either the birth or death concept.

### ISSUE THREAD

**Issue by tishyac3141** [Medical-Event-Data-Standard/meds_etl#18]
I'm trying to run the meds_omop_etl command to convert from a csv file of my data that uses OMOP over to the meds format. I'm getting the error that I've attached a screenshot of.
For reference, I'm working within the All of Us workbench which has a Jupyter Cloud Environment with 4 CPUs, 15 GB RAM, and one NVIDIA Tesla T4 GPU. I'm also using anaconda3, Python 3.11.5, and I've got femr and CLMBR installed and working. 

_side note: this is my first time opening a Github issue so forgive me if I've provided too little/inadequate information._

<img width="1009" alt="meds_etl_error" src="https://github.com/Medical-Event-Data-Standard/meds_etl/assets/44046096/bae2c6f9-a7c7-43f9-9b97-41996679d7ee">

**Comment by EthanSteinberg** [comment]
Hi Tishya,

Can you share that notebook with my AllOfUs account so I can take a look? My username is ethansteinberg@researchallofus.org.

Also, can you send me your AllOfUs username? I'll share my TestingMedsETL notebook that I used to verify that our code work on AllOfUs data.

You should also read https://github.com/Medical-Event-Data-Standard/meds/issues/17. As noted there, we need a better way to handle AllOfUs data. You and @zakcay might want to work together on that.

**Comment by EthanSteinberg** [comment]
Pay special attention to https://github.com/Medical-Event-Data-Standard/meds/issues/17#issuecomment-2032111704  in particular

**Comment by tishyac3141** [comment]
Hi Ethan,

Thank you!! I shared my workspace with you. Here's my allofus username: tishyac3.141@researchallofus.org

**Comment by EthanSteinberg** [comment]
@tishyac3141  I got your invite and sent you the invite to my workspace that I used for testing the ETL.

What is the name of your notebook that downloads the OMOP data into your workspace from BigQuery and runs the ETL?

Can you make a single notebook that does both the ETL and download step (like in my example workspace)?

**Comment by EthanSteinberg** [comment]
@tishyac3141 I think this is resolved so I am going to close this issue. Feel free to reopen if you continue to have problems.
