### ISSUE TITLE
meds_flat functionality

### ISSUE THREAD

**Issue by rvandewater** [Medical-Event-Data-Standard/meds_etl#23]
This is regarding the function convert_flat_to_meds and convert_meds_to_flat in meds 0.1.1
- [ ] When an error occurs, should we clean up the created meds directories? If you rerun it now, it will throw an error that the folder already exists.
- [x] Should we enforce the `data `or `flat_data` folder name for the source folder for meds_to_flat resp. flat_to_meds? ex,: https://github.com/Medical-Event-Data-Standard/meds_etl/blob/c799a0413507c3ca59626bbb7e8a12e2122190d1/src/meds_etl/flat.py#L79C1-L79C67. This seems strange when I used it to convert my data.

**Comment by EthanSteinberg** [comment]
>  When an error occurs, should we clean up the created meds directories? If you rerun it now, it will throw an error that the folder already exists.

I don't think we should clean them up? Otherwise it's much harder to debug.

>  Should we enforce the data or flat_data folder name for the source folder for meds_to_flat resp. flat_to_meds? ex,: https://github.com/Medical-Event-Data-Standard/meds_etl/blob/c799a0413507c3ca59626bbb7e8a12e2122190d1/src/meds_etl/flat.py#L79C1-L79C67. This seems strange when I used it to convert my data.

I think we have to make some sort of naming assumption here? I agree we should add an assert to verify this and make this more clear in the spec documents.

**Comment by EthanSteinbergPrealize** [comment]
An error message has been added to assert that the data folder must exist
