### ISSUE TITLE
Support of converting other types of EHR to MEDS?

### ISSUE THREAD

**Issue by byangstat** [Medical-Event-Data-Standard/meds_etl#34]
Hello,

I am wondering if the current package supports converting other types of EHR data to the MEDS schema?

**Comment by EthanSteinberg** [comment]
No, this package only provides "out of the box" support for MIMIC-IV and OMOP. 

However, we provide a MEDS Unsorted tool that should make it easy for you to write ETLs from any EHR dataset.

Is there a particular public EHR dataset/schema that you would like to see support for? We can create an issue to add support for it.

Feel free to add code for additional datasets yourself of course.
